In [ ]:
import numpy as np
import pandas as pd
cancer = pd.read_csv("cancer.csv")
cancer.columns

# GROUP BY

In [14]:
cancer.groupby('diagnosis')['radius_mean'].agg(['mean', 'min'])

                mean     min
diagnosis
B          12.146524   6.981
M          17.462830  10.950

In [15]:
cancer.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst'],
      dtype='object')

In [16]:
census.head()
census.describe().round()
census.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3193 entries, 0 to 3192
Data columns (total 100 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SUMLEV                 3193 non-null   int64
 1   REGION                 3193 non-null   int64
 2   DIVISION               3193 non-null   int64
 3   STATE                  3193 non-null   int64
 4   COUNTY                 3193 non-null   int64
 5   STNAME                 3193 non-null   object
 6   CTYNAME                3193 non-null   object
 7   CENSUS2010POP          3193 non-null   int64
 8   ESTIMATESBASE2010      3193 non-null   int64
 9   POPESTIMATE2010        3193 non-null   int64
 10  POPESTIMATE2011        3193 non-null   int64
 11  POPESTIMATE2012        3193 non-null   int64
 12  POPESTIMATE2013        3193 non-null   int64
 13  POPESTIMATE2014        3193 non-null   int64
 14  POPESTIMATE2015        3193 non-null   int64
 15  NPOPCHG_2010           3193 non-null   int64
 16  NPOPCHG_2011           3193 non-null   int64
 17  NPOPCHG_2012           3193 non-null   int64
 18  NPOPCHG_2013           3193 non-null   int64
 19  NPOPCHG_2014           3193 non-null   int64
 20  NPOPCHG_2015           3193 non-null   int64
 21  BIRTHS2010             3193 non-null   int64
 22  BIRTHS2011             3193 non-null   int64
 23  BIRTHS2012             3193 non-null   int64
 24  BIRTHS2013             3193 non-null   int64
 25  BIRTHS2014             3193 non-null   int64
 26  BIRTHS2015             3193 non-null   int64
 27  DEATHS2010             3193 non-null   int64
 28  DEATHS2011             3193 non-null   int64
 29  DEATHS2012             3193 non-null   int64
 30  DEATHS2013             3193 non-null   int64
 31  DEATHS2014             3193 non-null   int64
 32  DEATHS2015             3193 non-null   int64
 33  NATURALINC2010         3193 non-null   int64
 34  NATURALINC2011         3193 non-null   int64
 35  NATURALINC2012         3193 non-null   int64
 36  NATURALINC2013         3193 non-null   int64
 37  NATURALINC2014         3193 non-null   int64
 38  NATURALINC2015         3193 non-null   int64
 39  INTERNATIONALMIG2010   3193 non-null   int64
 40  INTERNATIONALMIG2011   3193 non-null   int64
 41  INTERNATIONALMIG2012   3193 non-null   int64
 42  INTERNATIONALMIG2013   3193 non-null   int64
 43  INTERNATIONALMIG2014   3193 non-null   int64
 44  INTERNATIONALMIG2015   3193 non-null   int64
 45  DOMESTICMIG2010        3193 non-null   int64
 46  DOMESTICMIG2011        3193 non-null   int64
 47  DOMESTICMIG2012        3193 non-null   int64
 48  DOMESTICMIG2013        3193 non-null   int64
 49  DOMESTICMIG2014        3193 non-null   int64
 50  DOMESTICMIG2015        3193 non-null   int64
 51  NETMIG2010             3193 non-null   int64
 52  NETMIG2011             3193 non-null   int64
 53  NETMIG2012             3193 non-null   int64
 54  NETMIG2013             3193 non-null   int64
 55  NETMIG2014             3193 non-null   int64
 56  NETMIG2015             3193 non-null   int64
 57  RESIDUAL2010           3193 non-null   int64
 58  RESIDUAL2011           3193 non-null   int64
 59  RESIDUAL2012           3193 non-null   int64
 60  RESIDUAL2013           3193 non-null   int64
 61  RESIDUAL2014           3193 non-null   int64
 62  RESIDUAL2015           3193 non-null   int64
 63  GQESTIMATESBASE2010    3193 non-null   int64
 64  GQESTIMATES2010        3193 non-null   int64
 65  GQESTIMATES2011        3193 non-null   int64
 66  GQESTIMATES2012        3193 non-null   int64
 67  GQESTIMATES2013        3193 non-null   int64
 68  GQESTIMATES2014        3193 non-null   int64
 69  GQESTIMATES2015        3193 non-null   int64
 70  RBIRTH2011             3193 non-null   float64
 71  RBIRTH2012             3193 non-null   float64
 72  RBIRTH2013             3193 non-null   float64
 73  RBIRTH2014             3193 non-null   float64
 74  RBIRTH2015             3193 non-null   float64
 75  RDEATH2011             3193 non-null   float64
 76  RDEATH2012             3193 non-null   float64
 77  RDEATH2013             3193 non-null   float64
 78  RDEATH2014             3193 non-null   float64
 79  RDEATH2015             3193 non-null   float64
 80  RNATURALINC2011        3193 non-null   float64
 81  RNATURALINC2012        3193 non-null   float64
 82  RNATURALINC2013        3193 non-null   float64
 83  RNATURALINC2014        3193 non-null   float64
 84  RNATURALINC2015        3193 non-null   float64
 85  RINTERNATIONALMIG2011  3193 non-null   float64
 86  RINTERNATIONALMIG2012  3193 non-null   float64
 87  RINTERNATIONALMIG2013  3193 non-null   float64
 88  RINTERNATIONALMIG2014  3193 non-null   float64
 89  RINTERNATIONALMIG2015  3193 non-null   float64
 90  RDOMESTICMIG2011       3193 non-null   float64
 91  RDOMESTICMIG2012       3193 non-null   float64
 92  RDOMESTICMIG2013       3193 non-null   float64
 93  RDOMESTICMIG2014       3193 non-null   float64
 94  RDOMESTICMIG2015       3193 non-null   float64
 95  RNETMIG2011            3193 non-null   float64
 96  RNETMIG2012            3193 non-null   float64
 97  RNETMIG2013            3193 non-null   float64
 98  RNETMIG2014            3193 non-null   float64
 99  RNETMIG2015            3193 non-null   float64
dtypes: float64(30), int64(68), object(2)
memory usage: 2.4+ MB

In [17]:
census.groupby('STNAME')['POPESTIMATE2010'].agg( maximum = 'max', minimum = 'min', mean = 'mean').round().sort_values('maximum', ascending = False)

                       maximum  minimum       mean
STNAME
California            37334079     1159  1265562.0
Texas                 25244363       83   197995.0
New York              19402920     4834   615966.0
Florida               18849890     8339   554409.0
Illinois              12841249     4305   249345.0
Pennsylvania          12712014     5074   373883.0
Ohio                  11540766    13421   259343.0
Michigan               9877369     2144   235175.0
Georgia                9713454     1699   121418.0
North Carolina         9558979     4413   189287.0
New Jersey             8803881    65998   800353.0
Virginia               8025787     2294   119788.0
Washington             6743060     2265   337153.0
Massachusetts          6565036    10164   875338.0
Indiana                6490590     6110   139583.0
Arizona                6408208     8339   801026.0
Tennessee              6356585     5072   132429.0
Missouri               5996052     2155   103380.0
Maryland               5788409    20199   463073.0
Wisconsin              5690204     4265   155896.0
Minnesota              5310903     3541   120702.0
Colorado               5048254      704   155331.0
Alabama                4785161     9001   140740.0
South Carolina         4635894    10225   197272.0
Louisiana              4544951     5224   139845.0
Kentucky               4347937     2273    71867.0
Oregon                 3837972     1447   207458.0
Oklahoma               3759596     2457    96400.0
Connecticut            3579717   118593   795493.0
Iowa                   3050694     4026    61014.0
Mississippi            2970316     1394    71574.0
Arkansas               2922394     5338    76905.0
Kansas                 2858824     1258    53940.0
Utah                   2775426     1074   185028.0
Nevada                 2703440      782   300382.0
New Mexico             2064741      687   121455.0
West Virginia          1854225     5745    66222.0
Nebraska               1830025      464    38937.0
Idaho                  1570986      979    69822.0
Hawaii                 1363980       90   454660.0
Maine                  1327695    17546   156199.0
New Hampshire          1316708    32980   239401.0
Rhode Island           1053219    49864   351073.0
Montana                 990643      492    34759.0
Delaware                899791   162990   449896.0
South Dakota            816299     1005    24367.0
Alaska                  714021      662    47601.0
North Dakota            674530      729    24983.0
Vermont                 625984     6302    83465.0
District of Columbia    605126   605126   605126.0
Wyoming                 564516     2492    47043.0

# Fetching Specific data

In [18]:
cancer[cancer['diagnosis'] == 'B']

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
19,8510426,B,13.540,14.36,87.46,566.3,0.09779,0.08129,0.06664,0.047810,...,15.110,19.26,99.70,711.2,0.14400,0.17730,0.23900,0.12880,0.2977,0.07259
20,8510653,B,13.080,15.71,85.63,520.0,0.10750,0.12700,0.04568,0.031100,...,14.500,20.49,96.09,630.5,0.13120,0.27760,0.18900,0.07283,0.3184,0.08183
21,8510824,B,9.504,12.44,60.34,273.9,0.10240,0.06492,0.02956,0.020760,...,10.230,15.66,65.13,314.9,0.13240,0.11480,0.08867,0.06227,0.2450,0.07773
37,854941,B,13.030,18.42,82.61,523.8,0.08983,0.03766,0.02562,0.029230,...,13.300,22.81,84.46,545.9,0.09701,0.04619,0.04833,0.05013,0.1987,0.06169
46,85713702,B,8.196,16.84,51.71,201.9,0.08600,0.05943,0.01588,0.005917,...,8.964,21.96,57.26,242.2,0.12970,0.13570,0.06880,0.02564,0.3105,0.07409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558,925277,B,14.590,22.68,96.39,657.1,0.08473,0.13300,0.10290,0.037360,...,15.480,27.27,105.90,733.5,0.10260,0.31710,0.36620,0.11050,0.2258,0.08004
559,925291,B,11.510,23.93,74.52,403.5,0.09261,0.10210,0.11120,0.041050,...,12.480,37.16,82.28,474.2,0.12980,0.25170,0.36300,0.09653,0.2112,0.08732
560,925292,B,14.050,27.15,91.38,600.4,0.09929,0.11260,0.04462,0.043040,...,15.300,33.17,100.20,706.7,0.12410,0.22640,0.13260,0.10480,0.2250,0.08321
561,925311,B,11.200,29.37,70.67,386.0,0.07449,0.03558,0.00000,0.000000,...,11.920,38.30,75.19,439.6,0.09267,0.05494,0.00000,0.00000,0.1566,0.05905
568,92751,B,7.760,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.000000,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.00000,0.00000,0.2871,0.07039

In [8]:
cancer['diagnosis']

0      M
1      M
2      M
3      M
4      M
          ...
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [25]:
census = pd.read_csv("census.csv")

In [ ]:
census.STNAME.value_counts()

STNAME
Texas                   255
Georgia                 160
Virginia                134
Kentucky                121
Missouri                116
Kansas                  106
Illinois                103
North Carolina          101
Iowa                    100
Tennessee                96
Nebraska                 94
Indiana                  93
Ohio                     89
Minnesota                88
Michigan                 84
Mississippi              83
Oklahoma                 78
Arkansas                 76
Wisconsin                73
Pennsylvania             68
Alabama                  68
Florida                  68
South Dakota             67
Louisiana                65
Colorado                 65
New York                 63
California               59
Montana                  57
West Virginia            56
North Dakota             54
South Carolina           47
Idaho                    45
Washington               40
Oregon                   37
New Mexico               34
Utah                     30
Alaska                   30
Maryland                 25
Wyoming                  24
New Jersey               22
Nevada                   18
Maine                    17
Arizona                  16
Vermont                  15
Massachusetts            15
New Hampshire            11
Connecticut               9
Hawaii                    6
Rhode Island              6
Delaware                  4
District of Columbia      2
Name: count, dtype: int64